apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: haez91jnl-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/haez91jnl-java-springboot-gitops